# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(default='', max_length=24)),
                ('value', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(default='', max_length=24)),
                ('value', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('text', models.TextField(default='')),
                ('language', models.CharField(choices=[('python', 'Python'), ('bash', 'Bash'), ('c', 'C Language'), ('cpp', 'C++ Language'), ('java', 'Java Language'), ('scilab', 'Scilab')], default='python', max_length=24)),
                ('marks', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'approved'), (0, 'unseen'), (-1, 'discarded')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Verygood'), (5, 'Excellent')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(choices=[(1, 'easy'), (2, 'medium'), (3, 'difficult')], max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_inputs', models.IntegerField()),
                ('no_of_outputs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interface.Question')),
                ('function_name', models.CharField(default=False, max_length=100)),
            ],
            bases=('interface.question',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interface.Question')),
                ('no_of_inputs', models.IntegerField(default=4)),
            ],
            bases=('interface.question',),
        ),
        migrations.AddField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Question'),
        ),
        migrations.AddField(
            model_name='review',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Question'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Question'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='output',
            name='test_cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.TestCase'),
        ),
        migrations.AddField(
            model_name='input',
            name='test_cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.TestCase'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Question'),
        ),
    ]
