# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20160611_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequestion',
            name='function_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='_type',
            field=models.CharField(choices=[(1, 'integer'), (2, 'float'), (3, 'string'), (4, 'boolean')], max_length=24),
        ),
        migrations.AlterField(
            model_name='output',
            name='_type',
            field=models.CharField(choices=[(1, 'integer'), (2, 'float'), (3, 'string'), (4, 'boolean')], max_length=24),
        ),
    ]
