# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20160624_1632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([]),
        ),
    ]
